### PR TITLE
Capacitor Energy Update

### PR DESCRIPTION
**Pull request by Vsalinas91**
Changes to the capacitor energy model to reflect the current technique used in our COMMAS synthetic flash analysis.

### CODE REVIEW

**Comment by Vsalinas91** [comment]
Previous charge density retrieval method (power-law) removed - constants changed to kwargs for the functions specified.

**Comment by Vsalinas91** [comment]
Don't merge yet, I was just leaving a comment.

**Comment by deeplycloudy** [comment]
I saw a final commit … this looks good to me. Are you ok with merging @Vsalinas91 ?

**Comment by Vsalinas91** [comment]
Sure thing. The output of my most recent test looks fine, so I think everything is good to go.

**Comment by deeplycloudy** [comment]
Thanks, @Vsalinas91!

**Pull request merged**
